version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    reviewers:
      - "Eden7600"
    labels:
      - "dependencies"
      - "npm"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
    reviewers:
      - "Eden7600"
    labels:
      - "ci"
      - "github-actions"
